import { HelpRequest } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { ChatPannel } from "../components/ChatPanel";
import { useRTM } from "../hooks/useRTM";
import { trpc } from "../utils/trpc";

const AdminPage: NextPage = () => {
  const helpRequestsQuery = trpc.helpRequest.getHelpRequests.useQuery();
  const [text, setText] = useState("");
  const { messages, clearMessages, connectTo, sendMessage } = useRTM();

  const handleHelpRequestClicked = async (helpRequest: HelpRequest) => {
    clearMessages();
    connectTo(helpRequest.id);
  };

  const handleSendMessage = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    sendMessage(text);
    setText("");
  };

  return (
    <>
      <Head>
        <title>Admin Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col p-4">
        <h1 className="mb-4 text-3xl">Admin Page</h1>

        <section className="flex gap-8">
          <div className="mb-2 rounded bg-white p-4">
            <h2 className="mb-2 text-xl">Help Request Ids</h2>
            <div className="flex flex-col gap-2">
              {helpRequestsQuery.data?.map((helpRequest) => (
                <button
                  className="hover:text-blue-400"
                  onClick={() => handleHelpRequestClicked(helpRequest)}
                  key={helpRequest.id}
                >
                  {helpRequest.id}
                </button>
              ))}
            </div>
          </div>

          <ChatPannel
            text={text}
            setText={setText}
            messages={messages}
            handleSendMessage={handleSendMessage}
          />
        </section>
      </main>
    </>
  );
};

export default AdminPage;
